import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header
          style={{
            background: "lightblue",
            padding: "1rem",
            marginBottom: "1rem",
          }}
        >
          <p className="text-lg font-bold">Header</p>
        </header>

        {children}

        <footer
          style={{
            background: "ghostwhite",
            padding: "1rem",
            marginTop: "1rem",
          }}
        >
          <p className="text-lg font-bold">Footer</p>
        </footer>
      </body>
    </html>
  );
}
