import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="flex justify-between items-center p-4 bg-gray-800 text-white">
          <p className="text-lg font-bold">Navbar</p>
          <ul className="flex space-x-12">
            <li className="hover:text-gray-400 cursor-pointer">Home</li>
            <li className="hover:text-gray-400 cursor-pointer">About Us</li>
            <li className="hover:text-gray-400 cursor-pointer">Product</li>
            <li className="hover:text-gray-400 cursor-pointer">Contact Us</li>
          </ul>
          <div>
            <button className="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">
              Click Me
            </button>
          </div>
        </nav>
        {children}

        <footer className="bg-gray-800 text-white text-center py-4">
          <p>Footer</p>
        </footer>
      </body>
    </html>
  );
}
